easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\BlogPost
        - App\Entity\Faculty
        - App\Entity\Department
        - App\Entity\User
        - App\Entity\Poster
        - App\Entity\Comment
